/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IncidentsIncidentIdRouteImport } from './routes/incidents.$incidentId'
import { Route as ConfigEscalationRouteImport } from './routes/config.escalation'
import { Route as ConfigAssigneesRouteImport } from './routes/config.assignees'

const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIncidentIdRoute = IncidentsIncidentIdRouteImport.update({
  id: '/incidents/$incidentId',
  path: '/incidents/$incidentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigEscalationRoute = ConfigEscalationRouteImport.update({
  id: '/escalation',
  path: '/escalation',
  getParentRoute: () => ConfigRoute,
} as any)
const ConfigAssigneesRoute = ConfigAssigneesRouteImport.update({
  id: '/assignees',
  path: '/assignees',
  getParentRoute: () => ConfigRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof ConfigRouteWithChildren
  '/config/assignees': typeof ConfigAssigneesRoute
  '/config/escalation': typeof ConfigEscalationRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof ConfigRouteWithChildren
  '/config/assignees': typeof ConfigAssigneesRoute
  '/config/escalation': typeof ConfigEscalationRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config': typeof ConfigRouteWithChildren
  '/config/assignees': typeof ConfigAssigneesRoute
  '/config/escalation': typeof ConfigEscalationRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/config/assignees'
    | '/config/escalation'
    | '/incidents/$incidentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config'
    | '/config/assignees'
    | '/config/escalation'
    | '/incidents/$incidentId'
  id:
    | '__root__'
    | '/'
    | '/config'
    | '/config/assignees'
    | '/config/escalation'
    | '/incidents/$incidentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRoute: typeof ConfigRouteWithChildren
  IncidentsIncidentIdRoute: typeof IncidentsIncidentIdRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$incidentId': {
      id: '/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof IncidentsIncidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/escalation': {
      id: '/config/escalation'
      path: '/escalation'
      fullPath: '/config/escalation'
      preLoaderRoute: typeof ConfigEscalationRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/config/assignees': {
      id: '/config/assignees'
      path: '/assignees'
      fullPath: '/config/assignees'
      preLoaderRoute: typeof ConfigAssigneesRouteImport
      parentRoute: typeof ConfigRoute
    }
  }
}

interface ConfigRouteChildren {
  ConfigAssigneesRoute: typeof ConfigAssigneesRoute
  ConfigEscalationRoute: typeof ConfigEscalationRoute
}

const ConfigRouteChildren: ConfigRouteChildren = {
  ConfigAssigneesRoute: ConfigAssigneesRoute,
  ConfigEscalationRoute: ConfigEscalationRoute,
}

const ConfigRouteWithChildren =
  ConfigRoute._addFileChildren(ConfigRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRoute: ConfigRouteWithChildren,
  IncidentsIncidentIdRoute: IncidentsIncidentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
