/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthErrorRouteImport } from './routes/auth.error'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedCatalogRouteImport } from './routes/_authed.catalog'
import { Route as ApiMetricsIndexRouteImport } from './routes/api/metrics/index'
import { Route as AuthedMetricsIndexRouteImport } from './routes/_authed.metrics/index'
import { Route as SlackOauthCallbackRouteImport } from './routes/slack/oauth/callback'
import { Route as NotionOauthCallbackRouteImport } from './routes/notion/oauth/callback'
import { Route as ApiRotationsStartWorkflowRouteImport } from './routes/api/rotations/start-workflow'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedTeamsTeamIdRouteImport } from './routes/_authed.teams/$teamId'
import { Route as AuthedStatusPageStatusPageIdRouteImport } from './routes/_authed.status-page/$statusPageId'
import { Route as AuthedServicesServiceIdRouteImport } from './routes/_authed.services/$serviceId'
import { Route as AuthedRotationsRotationIdRouteImport } from './routes/_authed.rotations/$rotationId'
import { Route as AuthedMetricsIncidentIdRouteImport } from './routes/_authed.metrics/$incidentId'
import { Route as AuthedIncidentsIncidentIdRouteImport } from './routes/_authed.incidents/$incidentId'
import { Route as AuthedCatalogTeamsRouteImport } from './routes/_authed.catalog.teams'
import { Route as AuthedCatalogStatusPagesRouteImport } from './routes/_authed.catalog.status-pages'
import { Route as AuthedCatalogServicesRouteImport } from './routes/_authed.catalog.services'
import { Route as AuthedCatalogRotationRouteImport } from './routes/_authed.catalog.rotation'
import { Route as AuthedCatalogEntryPointsRouteImport } from './routes/_authed.catalog.entry-points'
import { Route as AuthedTeamsTeamIdUsersRouteImport } from './routes/_authed.teams/$teamId.users'
import { Route as AuthedTeamsTeamIdServicesRouteImport } from './routes/_authed.teams/$teamId.services'
import { Route as AuthedTeamsTeamIdRotationsRouteImport } from './routes/_authed.teams/$teamId.rotations'
import { Route as AuthedTeamsTeamIdEntryPointsRouteImport } from './routes/_authed.teams/$teamId.entry-points'
import { Route as AuthedSettingsWorkspaceProfileRouteImport } from './routes/_authed.settings.workspace.profile'
import { Route as AuthedSettingsWorkspaceIntegrationsRouteImport } from './routes/_authed.settings.workspace.integrations'
import { Route as AuthedSettingsAccountProfileRouteImport } from './routes/_authed.settings.account.profile'
import { Route as AuthedSettingsAccountIntegrationsRouteImport } from './routes/_authed.settings.account.integrations'
import { Route as AuthedSettingsAccountApiKeysRouteImport } from './routes/_authed.settings.account.api-keys'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCatalogRoute = AuthedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiMetricsIndexRoute = ApiMetricsIndexRouteImport.update({
  id: '/api/metrics/',
  path: '/api/metrics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMetricsIndexRoute = AuthedMetricsIndexRouteImport.update({
  id: '/metrics/',
  path: '/metrics/',
  getParentRoute: () => AuthedRoute,
} as any)
const SlackOauthCallbackRoute = SlackOauthCallbackRouteImport.update({
  id: '/slack/oauth/callback',
  path: '/slack/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const NotionOauthCallbackRoute = NotionOauthCallbackRouteImport.update({
  id: '/notion/oauth/callback',
  path: '/notion/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRotationsStartWorkflowRoute =
  ApiRotationsStartWorkflowRouteImport.update({
    id: '/api/rotations/start-workflow',
    path: '/api/rotations/start-workflow',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTeamsTeamIdRoute = AuthedTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStatusPageStatusPageIdRoute =
  AuthedStatusPageStatusPageIdRouteImport.update({
    id: '/status-page/$statusPageId',
    path: '/status-page/$statusPageId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedServicesServiceIdRoute = AuthedServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRotationsRotationIdRoute =
  AuthedRotationsRotationIdRouteImport.update({
    id: '/rotations/$rotationId',
    path: '/rotations/$rotationId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedMetricsIncidentIdRoute = AuthedMetricsIncidentIdRouteImport.update({
  id: '/metrics/$incidentId',
  path: '/metrics/$incidentId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIncidentsIncidentIdRoute =
  AuthedIncidentsIncidentIdRouteImport.update({
    id: '/incidents/$incidentId',
    path: '/incidents/$incidentId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCatalogTeamsRoute = AuthedCatalogTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthedCatalogRoute,
} as any)
const AuthedCatalogStatusPagesRoute =
  AuthedCatalogStatusPagesRouteImport.update({
    id: '/status-pages',
    path: '/status-pages',
    getParentRoute: () => AuthedCatalogRoute,
  } as any)
const AuthedCatalogServicesRoute = AuthedCatalogServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthedCatalogRoute,
} as any)
const AuthedCatalogRotationRoute = AuthedCatalogRotationRouteImport.update({
  id: '/rotation',
  path: '/rotation',
  getParentRoute: () => AuthedCatalogRoute,
} as any)
const AuthedCatalogEntryPointsRoute =
  AuthedCatalogEntryPointsRouteImport.update({
    id: '/entry-points',
    path: '/entry-points',
    getParentRoute: () => AuthedCatalogRoute,
  } as any)
const AuthedTeamsTeamIdUsersRoute = AuthedTeamsTeamIdUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedTeamsTeamIdRoute,
} as any)
const AuthedTeamsTeamIdServicesRoute =
  AuthedTeamsTeamIdServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthedTeamsTeamIdRoute,
  } as any)
const AuthedTeamsTeamIdRotationsRoute =
  AuthedTeamsTeamIdRotationsRouteImport.update({
    id: '/rotations',
    path: '/rotations',
    getParentRoute: () => AuthedTeamsTeamIdRoute,
  } as any)
const AuthedTeamsTeamIdEntryPointsRoute =
  AuthedTeamsTeamIdEntryPointsRouteImport.update({
    id: '/entry-points',
    path: '/entry-points',
    getParentRoute: () => AuthedTeamsTeamIdRoute,
  } as any)
const AuthedSettingsWorkspaceProfileRoute =
  AuthedSettingsWorkspaceProfileRouteImport.update({
    id: '/workspace/profile',
    path: '/workspace/profile',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsWorkspaceIntegrationsRoute =
  AuthedSettingsWorkspaceIntegrationsRouteImport.update({
    id: '/workspace/integrations',
    path: '/workspace/integrations',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsAccountProfileRoute =
  AuthedSettingsAccountProfileRouteImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsAccountIntegrationsRoute =
  AuthedSettingsAccountIntegrationsRouteImport.update({
    id: '/account/integrations',
    path: '/account/integrations',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsAccountApiKeysRoute =
  AuthedSettingsAccountApiKeysRouteImport.update({
    id: '/account/api-keys',
    path: '/account/api-keys',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/catalog': typeof AuthedCatalogRouteWithChildren
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/auth/error': typeof AuthErrorRoute
  '/': typeof AuthedIndexRoute
  '/catalog/entry-points': typeof AuthedCatalogEntryPointsRoute
  '/catalog/rotation': typeof AuthedCatalogRotationRoute
  '/catalog/services': typeof AuthedCatalogServicesRoute
  '/catalog/status-pages': typeof AuthedCatalogStatusPagesRoute
  '/catalog/teams': typeof AuthedCatalogTeamsRoute
  '/incidents/$incidentId': typeof AuthedIncidentsIncidentIdRoute
  '/metrics/$incidentId': typeof AuthedMetricsIncidentIdRoute
  '/rotations/$rotationId': typeof AuthedRotationsRotationIdRoute
  '/services/$serviceId': typeof AuthedServicesServiceIdRoute
  '/status-page/$statusPageId': typeof AuthedStatusPageStatusPageIdRoute
  '/teams/$teamId': typeof AuthedTeamsTeamIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rotations/start-workflow': typeof ApiRotationsStartWorkflowRoute
  '/notion/oauth/callback': typeof NotionOauthCallbackRoute
  '/slack/oauth/callback': typeof SlackOauthCallbackRoute
  '/metrics': typeof AuthedMetricsIndexRoute
  '/api/metrics': typeof ApiMetricsIndexRoute
  '/settings/account/api-keys': typeof AuthedSettingsAccountApiKeysRoute
  '/settings/account/integrations': typeof AuthedSettingsAccountIntegrationsRoute
  '/settings/account/profile': typeof AuthedSettingsAccountProfileRoute
  '/settings/workspace/integrations': typeof AuthedSettingsWorkspaceIntegrationsRoute
  '/settings/workspace/profile': typeof AuthedSettingsWorkspaceProfileRoute
  '/teams/$teamId/entry-points': typeof AuthedTeamsTeamIdEntryPointsRoute
  '/teams/$teamId/rotations': typeof AuthedTeamsTeamIdRotationsRoute
  '/teams/$teamId/services': typeof AuthedTeamsTeamIdServicesRoute
  '/teams/$teamId/users': typeof AuthedTeamsTeamIdUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/catalog': typeof AuthedCatalogRouteWithChildren
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/auth/error': typeof AuthErrorRoute
  '/': typeof AuthedIndexRoute
  '/catalog/entry-points': typeof AuthedCatalogEntryPointsRoute
  '/catalog/rotation': typeof AuthedCatalogRotationRoute
  '/catalog/services': typeof AuthedCatalogServicesRoute
  '/catalog/status-pages': typeof AuthedCatalogStatusPagesRoute
  '/catalog/teams': typeof AuthedCatalogTeamsRoute
  '/incidents/$incidentId': typeof AuthedIncidentsIncidentIdRoute
  '/metrics/$incidentId': typeof AuthedMetricsIncidentIdRoute
  '/rotations/$rotationId': typeof AuthedRotationsRotationIdRoute
  '/services/$serviceId': typeof AuthedServicesServiceIdRoute
  '/status-page/$statusPageId': typeof AuthedStatusPageStatusPageIdRoute
  '/teams/$teamId': typeof AuthedTeamsTeamIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rotations/start-workflow': typeof ApiRotationsStartWorkflowRoute
  '/notion/oauth/callback': typeof NotionOauthCallbackRoute
  '/slack/oauth/callback': typeof SlackOauthCallbackRoute
  '/metrics': typeof AuthedMetricsIndexRoute
  '/api/metrics': typeof ApiMetricsIndexRoute
  '/settings/account/api-keys': typeof AuthedSettingsAccountApiKeysRoute
  '/settings/account/integrations': typeof AuthedSettingsAccountIntegrationsRoute
  '/settings/account/profile': typeof AuthedSettingsAccountProfileRoute
  '/settings/workspace/integrations': typeof AuthedSettingsWorkspaceIntegrationsRoute
  '/settings/workspace/profile': typeof AuthedSettingsWorkspaceProfileRoute
  '/teams/$teamId/entry-points': typeof AuthedTeamsTeamIdEntryPointsRoute
  '/teams/$teamId/rotations': typeof AuthedTeamsTeamIdRotationsRoute
  '/teams/$teamId/services': typeof AuthedTeamsTeamIdServicesRoute
  '/teams/$teamId/users': typeof AuthedTeamsTeamIdUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/catalog': typeof AuthedCatalogRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/auth/error': typeof AuthErrorRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/catalog/entry-points': typeof AuthedCatalogEntryPointsRoute
  '/_authed/catalog/rotation': typeof AuthedCatalogRotationRoute
  '/_authed/catalog/services': typeof AuthedCatalogServicesRoute
  '/_authed/catalog/status-pages': typeof AuthedCatalogStatusPagesRoute
  '/_authed/catalog/teams': typeof AuthedCatalogTeamsRoute
  '/_authed/incidents/$incidentId': typeof AuthedIncidentsIncidentIdRoute
  '/_authed/metrics/$incidentId': typeof AuthedMetricsIncidentIdRoute
  '/_authed/rotations/$rotationId': typeof AuthedRotationsRotationIdRoute
  '/_authed/services/$serviceId': typeof AuthedServicesServiceIdRoute
  '/_authed/status-page/$statusPageId': typeof AuthedStatusPageStatusPageIdRoute
  '/_authed/teams/$teamId': typeof AuthedTeamsTeamIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rotations/start-workflow': typeof ApiRotationsStartWorkflowRoute
  '/notion/oauth/callback': typeof NotionOauthCallbackRoute
  '/slack/oauth/callback': typeof SlackOauthCallbackRoute
  '/_authed/metrics/': typeof AuthedMetricsIndexRoute
  '/api/metrics/': typeof ApiMetricsIndexRoute
  '/_authed/settings/account/api-keys': typeof AuthedSettingsAccountApiKeysRoute
  '/_authed/settings/account/integrations': typeof AuthedSettingsAccountIntegrationsRoute
  '/_authed/settings/account/profile': typeof AuthedSettingsAccountProfileRoute
  '/_authed/settings/workspace/integrations': typeof AuthedSettingsWorkspaceIntegrationsRoute
  '/_authed/settings/workspace/profile': typeof AuthedSettingsWorkspaceProfileRoute
  '/_authed/teams/$teamId/entry-points': typeof AuthedTeamsTeamIdEntryPointsRoute
  '/_authed/teams/$teamId/rotations': typeof AuthedTeamsTeamIdRotationsRoute
  '/_authed/teams/$teamId/services': typeof AuthedTeamsTeamIdServicesRoute
  '/_authed/teams/$teamId/users': typeof AuthedTeamsTeamIdUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/catalog'
    | '/settings'
    | '/api/upload'
    | '/auth/error'
    | '/'
    | '/catalog/entry-points'
    | '/catalog/rotation'
    | '/catalog/services'
    | '/catalog/status-pages'
    | '/catalog/teams'
    | '/incidents/$incidentId'
    | '/metrics/$incidentId'
    | '/rotations/$rotationId'
    | '/services/$serviceId'
    | '/status-page/$statusPageId'
    | '/teams/$teamId'
    | '/api/auth/$'
    | '/api/rotations/start-workflow'
    | '/notion/oauth/callback'
    | '/slack/oauth/callback'
    | '/metrics'
    | '/api/metrics'
    | '/settings/account/api-keys'
    | '/settings/account/integrations'
    | '/settings/account/profile'
    | '/settings/workspace/integrations'
    | '/settings/workspace/profile'
    | '/teams/$teamId/entry-points'
    | '/teams/$teamId/rotations'
    | '/teams/$teamId/services'
    | '/teams/$teamId/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/catalog'
    | '/settings'
    | '/api/upload'
    | '/auth/error'
    | '/'
    | '/catalog/entry-points'
    | '/catalog/rotation'
    | '/catalog/services'
    | '/catalog/status-pages'
    | '/catalog/teams'
    | '/incidents/$incidentId'
    | '/metrics/$incidentId'
    | '/rotations/$rotationId'
    | '/services/$serviceId'
    | '/status-page/$statusPageId'
    | '/teams/$teamId'
    | '/api/auth/$'
    | '/api/rotations/start-workflow'
    | '/notion/oauth/callback'
    | '/slack/oauth/callback'
    | '/metrics'
    | '/api/metrics'
    | '/settings/account/api-keys'
    | '/settings/account/integrations'
    | '/settings/account/profile'
    | '/settings/workspace/integrations'
    | '/settings/workspace/profile'
    | '/teams/$teamId/entry-points'
    | '/teams/$teamId/rotations'
    | '/teams/$teamId/services'
    | '/teams/$teamId/users'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/catalog'
    | '/_authed/settings'
    | '/api/upload'
    | '/auth/error'
    | '/_authed/'
    | '/_authed/catalog/entry-points'
    | '/_authed/catalog/rotation'
    | '/_authed/catalog/services'
    | '/_authed/catalog/status-pages'
    | '/_authed/catalog/teams'
    | '/_authed/incidents/$incidentId'
    | '/_authed/metrics/$incidentId'
    | '/_authed/rotations/$rotationId'
    | '/_authed/services/$serviceId'
    | '/_authed/status-page/$statusPageId'
    | '/_authed/teams/$teamId'
    | '/api/auth/$'
    | '/api/rotations/start-workflow'
    | '/notion/oauth/callback'
    | '/slack/oauth/callback'
    | '/_authed/metrics/'
    | '/api/metrics/'
    | '/_authed/settings/account/api-keys'
    | '/_authed/settings/account/integrations'
    | '/_authed/settings/account/profile'
    | '/_authed/settings/workspace/integrations'
    | '/_authed/settings/workspace/profile'
    | '/_authed/teams/$teamId/entry-points'
    | '/_authed/teams/$teamId/rotations'
    | '/_authed/teams/$teamId/services'
    | '/_authed/teams/$teamId/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiUploadRoute: typeof ApiUploadRoute
  AuthErrorRoute: typeof AuthErrorRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRotationsStartWorkflowRoute: typeof ApiRotationsStartWorkflowRoute
  NotionOauthCallbackRoute: typeof NotionOauthCallbackRoute
  SlackOauthCallbackRoute: typeof SlackOauthCallbackRoute
  ApiMetricsIndexRoute: typeof ApiMetricsIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/catalog': {
      id: '/_authed/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthedCatalogRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/metrics/': {
      id: '/api/metrics/'
      path: '/api/metrics'
      fullPath: '/api/metrics'
      preLoaderRoute: typeof ApiMetricsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/metrics/': {
      id: '/_authed/metrics/'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AuthedMetricsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/slack/oauth/callback': {
      id: '/slack/oauth/callback'
      path: '/slack/oauth/callback'
      fullPath: '/slack/oauth/callback'
      preLoaderRoute: typeof SlackOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notion/oauth/callback': {
      id: '/notion/oauth/callback'
      path: '/notion/oauth/callback'
      fullPath: '/notion/oauth/callback'
      preLoaderRoute: typeof NotionOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rotations/start-workflow': {
      id: '/api/rotations/start-workflow'
      path: '/api/rotations/start-workflow'
      fullPath: '/api/rotations/start-workflow'
      preLoaderRoute: typeof ApiRotationsStartWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/teams/$teamId': {
      id: '/_authed/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthedTeamsTeamIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/status-page/$statusPageId': {
      id: '/_authed/status-page/$statusPageId'
      path: '/status-page/$statusPageId'
      fullPath: '/status-page/$statusPageId'
      preLoaderRoute: typeof AuthedStatusPageStatusPageIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/services/$serviceId': {
      id: '/_authed/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof AuthedServicesServiceIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/rotations/$rotationId': {
      id: '/_authed/rotations/$rotationId'
      path: '/rotations/$rotationId'
      fullPath: '/rotations/$rotationId'
      preLoaderRoute: typeof AuthedRotationsRotationIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/metrics/$incidentId': {
      id: '/_authed/metrics/$incidentId'
      path: '/metrics/$incidentId'
      fullPath: '/metrics/$incidentId'
      preLoaderRoute: typeof AuthedMetricsIncidentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/incidents/$incidentId': {
      id: '/_authed/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof AuthedIncidentsIncidentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/catalog/teams': {
      id: '/_authed/catalog/teams'
      path: '/teams'
      fullPath: '/catalog/teams'
      preLoaderRoute: typeof AuthedCatalogTeamsRouteImport
      parentRoute: typeof AuthedCatalogRoute
    }
    '/_authed/catalog/status-pages': {
      id: '/_authed/catalog/status-pages'
      path: '/status-pages'
      fullPath: '/catalog/status-pages'
      preLoaderRoute: typeof AuthedCatalogStatusPagesRouteImport
      parentRoute: typeof AuthedCatalogRoute
    }
    '/_authed/catalog/services': {
      id: '/_authed/catalog/services'
      path: '/services'
      fullPath: '/catalog/services'
      preLoaderRoute: typeof AuthedCatalogServicesRouteImport
      parentRoute: typeof AuthedCatalogRoute
    }
    '/_authed/catalog/rotation': {
      id: '/_authed/catalog/rotation'
      path: '/rotation'
      fullPath: '/catalog/rotation'
      preLoaderRoute: typeof AuthedCatalogRotationRouteImport
      parentRoute: typeof AuthedCatalogRoute
    }
    '/_authed/catalog/entry-points': {
      id: '/_authed/catalog/entry-points'
      path: '/entry-points'
      fullPath: '/catalog/entry-points'
      preLoaderRoute: typeof AuthedCatalogEntryPointsRouteImport
      parentRoute: typeof AuthedCatalogRoute
    }
    '/_authed/teams/$teamId/users': {
      id: '/_authed/teams/$teamId/users'
      path: '/users'
      fullPath: '/teams/$teamId/users'
      preLoaderRoute: typeof AuthedTeamsTeamIdUsersRouteImport
      parentRoute: typeof AuthedTeamsTeamIdRoute
    }
    '/_authed/teams/$teamId/services': {
      id: '/_authed/teams/$teamId/services'
      path: '/services'
      fullPath: '/teams/$teamId/services'
      preLoaderRoute: typeof AuthedTeamsTeamIdServicesRouteImport
      parentRoute: typeof AuthedTeamsTeamIdRoute
    }
    '/_authed/teams/$teamId/rotations': {
      id: '/_authed/teams/$teamId/rotations'
      path: '/rotations'
      fullPath: '/teams/$teamId/rotations'
      preLoaderRoute: typeof AuthedTeamsTeamIdRotationsRouteImport
      parentRoute: typeof AuthedTeamsTeamIdRoute
    }
    '/_authed/teams/$teamId/entry-points': {
      id: '/_authed/teams/$teamId/entry-points'
      path: '/entry-points'
      fullPath: '/teams/$teamId/entry-points'
      preLoaderRoute: typeof AuthedTeamsTeamIdEntryPointsRouteImport
      parentRoute: typeof AuthedTeamsTeamIdRoute
    }
    '/_authed/settings/workspace/profile': {
      id: '/_authed/settings/workspace/profile'
      path: '/workspace/profile'
      fullPath: '/settings/workspace/profile'
      preLoaderRoute: typeof AuthedSettingsWorkspaceProfileRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/workspace/integrations': {
      id: '/_authed/settings/workspace/integrations'
      path: '/workspace/integrations'
      fullPath: '/settings/workspace/integrations'
      preLoaderRoute: typeof AuthedSettingsWorkspaceIntegrationsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/account/profile': {
      id: '/_authed/settings/account/profile'
      path: '/account/profile'
      fullPath: '/settings/account/profile'
      preLoaderRoute: typeof AuthedSettingsAccountProfileRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/account/integrations': {
      id: '/_authed/settings/account/integrations'
      path: '/account/integrations'
      fullPath: '/settings/account/integrations'
      preLoaderRoute: typeof AuthedSettingsAccountIntegrationsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/account/api-keys': {
      id: '/_authed/settings/account/api-keys'
      path: '/account/api-keys'
      fullPath: '/settings/account/api-keys'
      preLoaderRoute: typeof AuthedSettingsAccountApiKeysRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
  }
}

interface AuthedCatalogRouteChildren {
  AuthedCatalogEntryPointsRoute: typeof AuthedCatalogEntryPointsRoute
  AuthedCatalogRotationRoute: typeof AuthedCatalogRotationRoute
  AuthedCatalogServicesRoute: typeof AuthedCatalogServicesRoute
  AuthedCatalogStatusPagesRoute: typeof AuthedCatalogStatusPagesRoute
  AuthedCatalogTeamsRoute: typeof AuthedCatalogTeamsRoute
}

const AuthedCatalogRouteChildren: AuthedCatalogRouteChildren = {
  AuthedCatalogEntryPointsRoute: AuthedCatalogEntryPointsRoute,
  AuthedCatalogRotationRoute: AuthedCatalogRotationRoute,
  AuthedCatalogServicesRoute: AuthedCatalogServicesRoute,
  AuthedCatalogStatusPagesRoute: AuthedCatalogStatusPagesRoute,
  AuthedCatalogTeamsRoute: AuthedCatalogTeamsRoute,
}

const AuthedCatalogRouteWithChildren = AuthedCatalogRoute._addFileChildren(
  AuthedCatalogRouteChildren,
)

interface AuthedSettingsRouteChildren {
  AuthedSettingsAccountApiKeysRoute: typeof AuthedSettingsAccountApiKeysRoute
  AuthedSettingsAccountIntegrationsRoute: typeof AuthedSettingsAccountIntegrationsRoute
  AuthedSettingsAccountProfileRoute: typeof AuthedSettingsAccountProfileRoute
  AuthedSettingsWorkspaceIntegrationsRoute: typeof AuthedSettingsWorkspaceIntegrationsRoute
  AuthedSettingsWorkspaceProfileRoute: typeof AuthedSettingsWorkspaceProfileRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsAccountApiKeysRoute: AuthedSettingsAccountApiKeysRoute,
  AuthedSettingsAccountIntegrationsRoute:
    AuthedSettingsAccountIntegrationsRoute,
  AuthedSettingsAccountProfileRoute: AuthedSettingsAccountProfileRoute,
  AuthedSettingsWorkspaceIntegrationsRoute:
    AuthedSettingsWorkspaceIntegrationsRoute,
  AuthedSettingsWorkspaceProfileRoute: AuthedSettingsWorkspaceProfileRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedTeamsTeamIdRouteChildren {
  AuthedTeamsTeamIdEntryPointsRoute: typeof AuthedTeamsTeamIdEntryPointsRoute
  AuthedTeamsTeamIdRotationsRoute: typeof AuthedTeamsTeamIdRotationsRoute
  AuthedTeamsTeamIdServicesRoute: typeof AuthedTeamsTeamIdServicesRoute
  AuthedTeamsTeamIdUsersRoute: typeof AuthedTeamsTeamIdUsersRoute
}

const AuthedTeamsTeamIdRouteChildren: AuthedTeamsTeamIdRouteChildren = {
  AuthedTeamsTeamIdEntryPointsRoute: AuthedTeamsTeamIdEntryPointsRoute,
  AuthedTeamsTeamIdRotationsRoute: AuthedTeamsTeamIdRotationsRoute,
  AuthedTeamsTeamIdServicesRoute: AuthedTeamsTeamIdServicesRoute,
  AuthedTeamsTeamIdUsersRoute: AuthedTeamsTeamIdUsersRoute,
}

const AuthedTeamsTeamIdRouteWithChildren =
  AuthedTeamsTeamIdRoute._addFileChildren(AuthedTeamsTeamIdRouteChildren)

interface AuthedRouteChildren {
  AuthedCatalogRoute: typeof AuthedCatalogRouteWithChildren
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedIncidentsIncidentIdRoute: typeof AuthedIncidentsIncidentIdRoute
  AuthedMetricsIncidentIdRoute: typeof AuthedMetricsIncidentIdRoute
  AuthedRotationsRotationIdRoute: typeof AuthedRotationsRotationIdRoute
  AuthedServicesServiceIdRoute: typeof AuthedServicesServiceIdRoute
  AuthedStatusPageStatusPageIdRoute: typeof AuthedStatusPageStatusPageIdRoute
  AuthedTeamsTeamIdRoute: typeof AuthedTeamsTeamIdRouteWithChildren
  AuthedMetricsIndexRoute: typeof AuthedMetricsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCatalogRoute: AuthedCatalogRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedIncidentsIncidentIdRoute: AuthedIncidentsIncidentIdRoute,
  AuthedMetricsIncidentIdRoute: AuthedMetricsIncidentIdRoute,
  AuthedRotationsRotationIdRoute: AuthedRotationsRotationIdRoute,
  AuthedServicesServiceIdRoute: AuthedServicesServiceIdRoute,
  AuthedStatusPageStatusPageIdRoute: AuthedStatusPageStatusPageIdRoute,
  AuthedTeamsTeamIdRoute: AuthedTeamsTeamIdRouteWithChildren,
  AuthedMetricsIndexRoute: AuthedMetricsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiUploadRoute: ApiUploadRoute,
  AuthErrorRoute: AuthErrorRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRotationsStartWorkflowRoute: ApiRotationsStartWorkflowRoute,
  NotionOauthCallbackRoute: NotionOauthCallbackRoute,
  SlackOauthCallbackRoute: SlackOauthCallbackRoute,
  ApiMetricsIndexRoute: ApiMetricsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
